In [1]:
from tensorflow.keras.preprocessing.text import one_hot

p:\NLP\ANN_project_implementation\venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good girl',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',
]

In [3]:
## define the vocabulary size

voc_size = 10000
one_hot_repr = [one_hot(word, voc_size) for word in sent]

In [4]:
one_hot_repr

[[8314, 6696, 6564, 9489],
 [8314, 6696, 6564, 6869],
 [8314, 4365, 6564, 6833],
 [1493, 100, 8644, 1335, 2924],
 [1493, 100, 8644, 1335, 3483],
 [4846, 8314, 3251, 6564, 8074],
 [1096, 3599, 3083, 1335]]

In [12]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [13]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8314 6696 6564 9489]
 [   0    0    0    0 8314 6696 6564 6869]
 [   0    0    0    0 8314 4365 6564 6833]
 [   0    0    0 1493  100 8644 1335 2924]
 [   0    0    0 1493  100 8644 1335 3483]
 [   0    0    0 4846 8314 3251 6564 8074]
 [   0    0    0    0 1096 3599 3083 1335]]


In [14]:
## feature representation

dim = 10
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[[ 2.57620476e-02, -1.61557198e-02, -2.82268524e-02,
         -1.73814520e-02, -3.46055254e-02,  2.27240473e-03,
          3.36161144e-02, -3.04515287e-03, -8.39766115e-03,
         -4.25982587e-02],
        [ 2.57620476e-02, -1.61557198e-02, -2.82268524e-02,
         -1.73814520e-02, -3.46055254e-02,  2.27240473e-03,
          3.36161144e-02, -3.04515287e-03, -8.39766115e-03,
         -4.25982587e-02],
        [ 2.57620476e-02, -1.61557198e-02, -2.82268524e-02,
         -1.73814520e-02, -3.46055254e-02,  2.27240473e-03,
          3.36161144e-02, -3.04515287e-03, -8.39766115e-03,
         -4.25982587e-02],
        [ 2.57620476e-02, -1.61557198e-02, -2.82268524e-02,
         -1.73814520e-02, -3.46055254e-02,  2.27240473e-03,
          3.36161144e-02, -3.04515287e-03, -8.39766115e-03,
         -4.25982587e-02],
        [-2.19597220e-02, -1.02204084e-02, -3.77173349e-03,
          9.85519961e-03, -1.28274560e-02, -1.94269307e-02,
          1.13205910e-02,  1.27106197e-02,  2.102276